### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by changcheng22023** [changcheng967/nixizhilu#3]
the secret code is too obvious

**Comment by changcheng967** [comment]
it is?

**Comment by changcheng22023** [comment]
yeah

**Comment by changcheng22023** [comment]
pretty much, you could littrerly press the button by accident

**Comment by changcheng967** [comment]
oh yeah

**Comment by changcheng967** [comment]
let me work on it

**Comment by changcheng6541** [comment]
I think it's fine

**Comment by DouletMedia** [comment]
> I think it's fine

agree

**Comment by changcheng967** [comment]
That's litterly what I thought

**Comment by changcheng967** [comment]
@changcheng22023 we'll reject that request because we'll wait if there's still people asking about it

**Comment by changcheng22023** [comment]
huh
